//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Data/DefaultControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DefaultControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DefaultControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DefaultControls"",
    ""maps"": [
        {
            ""name"": ""Player1"",
            ""id"": ""784064ec-2dba-4ab1-ad38-bf6c6ebd2483"",
            ""actions"": [
                {
                    ""name"": ""P1_ToggleCover"",
                    ""type"": ""Button"",
                    ""id"": ""9e2579b8-dc55-4fb0-8af8-a277034e7c3d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1_Aim"",
                    ""type"": ""Value"",
                    ""id"": ""d794466c-b6e6-403f-a317-a891406aba85"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P1_Fire"",
                    ""type"": ""Button"",
                    ""id"": ""69a8041e-d812-40ff-91fa-6f7b9b4a154b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""2a374259-2cb4-4a72-aec9-eb9c29fa6661"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""12055be8-e914-4dd4-84c9-1769ae710c2e"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P1_ToggleCover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""127ccb02-2a4c-41d8-8926-1805a8ea7e9d"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""P1_ToggleCover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0d36d5ca-401a-41b2-bf32-99b017f5ae7a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""P1_Aim"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""83b7f85b-f296-47bf-b5ff-a7fb4adfca4f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P1_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""abd7abff-c558-4e3e-9a87-46fee516395e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P1_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3c5f3097-738d-4db8-84bb-e2eee6c65890"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P1_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""61fc6e8e-7365-48c9-9a5f-1b9e12129f02"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P1_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d80d2e00-0d46-4f7b-99b3-e8fabd155e2f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""P1_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e381df75-2d2d-49a1-bfa6-e17e3815372e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P1_Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cc25eec-c3ce-4dd1-b291-d17216ccffeb"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""P1_Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4e981d6-0ff6-4b48-afb9-e51a92c5f111"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ec25d56-65c7-41bc-bf9f-55ecac98d5d5"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player2"",
            ""id"": ""bf5705f0-d001-4a2b-8c06-10e04af8fc30"",
            ""actions"": [
                {
                    ""name"": ""P2_ToggleCover"",
                    ""type"": ""Button"",
                    ""id"": ""2f0d059d-dc01-4406-86e5-596e1bb888e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2_Aim"",
                    ""type"": ""Value"",
                    ""id"": ""c2898912-406f-4bb4-ae77-8ecc5fc79e36"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P2_Fire"",
                    ""type"": ""Button"",
                    ""id"": ""c9910f97-1623-4af0-8edb-9850d120d4d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f63e9984-58eb-455f-a417-942f8e8658c6"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P2_ToggleCover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e94c6c3-4c9b-45af-a23e-0df63eda6c02"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""P2_ToggleCover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b048d45b-80eb-4e91-9312-690235874b38"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""P2_Aim"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b21ac3b6-d1d7-4c86-ab06-d56bd30e6c9d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P2_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f305d7d0-8ba5-4a9c-ad7e-9164661fdb04"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P2_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a9f804aa-0524-42aa-8391-5138518fea20"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P2_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""11ddd03a-3a88-4d70-98c4-f203d521c348"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P2_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7990a0b1-b002-4a21-a692-11280ccb4812"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""P2_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c36d5fe-8b4f-4ef8-8b65-7445219a784d"",
                    ""path"": ""<Keyboard>/rightCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""P2_Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c75f0b3-ed89-42b6-b332-dc36d2adca9e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""P2_Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player1UI"",
            ""id"": ""fcd7f278-072c-4d1c-8fb9-85d1b4cceed5"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""553fbac5-df45-437d-bd15-1a39ccbb42e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navitage"",
                    ""type"": ""Value"",
                    ""id"": ""5f30f35a-5a8d-4be1-b0ea-c1ea509010a5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""02bb9457-20c3-4088-88fb-9d12433c23df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4a00932c-8163-4fe9-b443-3b3df57decf3"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4635d131-e1bd-49c6-9d58-79f2ebafa0f7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bef30e9-5512-4f64-9dd6-6137679fa6b2"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7616ba0-5d56-4157-b44c-adcc3f6315d7"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f8cd4d0-5f2f-46e1-a449-c6ade6858bbb"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""589af910-9f89-4d0b-b7ae-81b4b3490fce"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b2e90132-5baa-4a7a-a8dd-3b79f26b631f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navitage"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e7fc087d-d78e-4cd2-816b-677db1bf5ab7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""97317cf3-16b8-4035-926c-f23dba803e2d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1b76e364-1f8a-4d61-9b1f-9e8228b1f09a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""52be9f15-6cee-4859-abfa-dc11262bf188"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Player2UI"",
            ""id"": ""889ac1c5-b202-48c9-b262-1820a12436f9"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""b41cd8f8-67df-4c9b-ac4a-7208f715fc48"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navitage"",
                    ""type"": ""Value"",
                    ""id"": ""3b36f480-b003-4aa4-b476-f6deac11b2d4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""5cc52b1c-638b-41f3-9d63-2386d96ad3c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d20f9354-1640-407f-af87-43123884b303"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""fc9d8ef2-1c9c-43b4-bb36-705e4f47467e"",
                    ""path"": ""2DVector"",
                    ""interactions"": ""Tap,Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navitage"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3db5064e-3c75-4091-8543-5586a3dee8b6"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2be7f14e-fca3-4fd0-88f8-25233158fe80"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a07b307e-c960-4027-962c-ccc11ebb35c8"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a75e38e0-0a44-45a8-ac29-a64f05c7d047"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""3604ea7d-547a-4c80-a3b8-c242ba7acf5a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navitage"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fa31d75f-05b0-4d1b-aa3c-913fcbf340f9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""67926b95-0bc8-4a85-801e-00753b6ae8c1"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""fe5cc7b4-e130-4a09-a39e-6ecf9d7bc738"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ff2d419d-765c-484f-8b8f-e7fb86bcce5e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Navitage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""02015ddc-5216-4eb1-bfff-1593f40b5299"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a694ae6-6d69-491b-8c6a-f46a380e9d29"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee388fc9-f6e1-4beb-a319-624aa6b2e05b"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59d403a3-6133-4362-906e-9e414142774a"",
                    ""path"": ""<Keyboard>/rightCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player1
        m_Player1 = asset.FindActionMap("Player1", throwIfNotFound: true);
        m_Player1_P1_ToggleCover = m_Player1.FindAction("P1_ToggleCover", throwIfNotFound: true);
        m_Player1_P1_Aim = m_Player1.FindAction("P1_Aim", throwIfNotFound: true);
        m_Player1_P1_Fire = m_Player1.FindAction("P1_Fire", throwIfNotFound: true);
        m_Player1_Pause = m_Player1.FindAction("Pause", throwIfNotFound: true);
        // Player2
        m_Player2 = asset.FindActionMap("Player2", throwIfNotFound: true);
        m_Player2_P2_ToggleCover = m_Player2.FindAction("P2_ToggleCover", throwIfNotFound: true);
        m_Player2_P2_Aim = m_Player2.FindAction("P2_Aim", throwIfNotFound: true);
        m_Player2_P2_Fire = m_Player2.FindAction("P2_Fire", throwIfNotFound: true);
        // Player1UI
        m_Player1UI = asset.FindActionMap("Player1UI", throwIfNotFound: true);
        m_Player1UI_Select = m_Player1UI.FindAction("Select", throwIfNotFound: true);
        m_Player1UI_Navitage = m_Player1UI.FindAction("Navitage", throwIfNotFound: true);
        m_Player1UI_Back = m_Player1UI.FindAction("Back", throwIfNotFound: true);
        // Player2UI
        m_Player2UI = asset.FindActionMap("Player2UI", throwIfNotFound: true);
        m_Player2UI_Select = m_Player2UI.FindAction("Select", throwIfNotFound: true);
        m_Player2UI_Navitage = m_Player2UI.FindAction("Navitage", throwIfNotFound: true);
        m_Player2UI_Back = m_Player2UI.FindAction("Back", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player1
    private readonly InputActionMap m_Player1;
    private IPlayer1Actions m_Player1ActionsCallbackInterface;
    private readonly InputAction m_Player1_P1_ToggleCover;
    private readonly InputAction m_Player1_P1_Aim;
    private readonly InputAction m_Player1_P1_Fire;
    private readonly InputAction m_Player1_Pause;
    public struct Player1Actions
    {
        private @DefaultControls m_Wrapper;
        public Player1Actions(@DefaultControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @P1_ToggleCover => m_Wrapper.m_Player1_P1_ToggleCover;
        public InputAction @P1_Aim => m_Wrapper.m_Player1_P1_Aim;
        public InputAction @P1_Fire => m_Wrapper.m_Player1_P1_Fire;
        public InputAction @Pause => m_Wrapper.m_Player1_Pause;
        public InputActionMap Get() { return m_Wrapper.m_Player1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer1Actions instance)
        {
            if (m_Wrapper.m_Player1ActionsCallbackInterface != null)
            {
                @P1_ToggleCover.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnP1_ToggleCover;
                @P1_ToggleCover.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnP1_ToggleCover;
                @P1_ToggleCover.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnP1_ToggleCover;
                @P1_Aim.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnP1_Aim;
                @P1_Aim.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnP1_Aim;
                @P1_Aim.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnP1_Aim;
                @P1_Fire.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnP1_Fire;
                @P1_Fire.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnP1_Fire;
                @P1_Fire.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnP1_Fire;
                @Pause.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_Player1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @P1_ToggleCover.started += instance.OnP1_ToggleCover;
                @P1_ToggleCover.performed += instance.OnP1_ToggleCover;
                @P1_ToggleCover.canceled += instance.OnP1_ToggleCover;
                @P1_Aim.started += instance.OnP1_Aim;
                @P1_Aim.performed += instance.OnP1_Aim;
                @P1_Aim.canceled += instance.OnP1_Aim;
                @P1_Fire.started += instance.OnP1_Fire;
                @P1_Fire.performed += instance.OnP1_Fire;
                @P1_Fire.canceled += instance.OnP1_Fire;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public Player1Actions @Player1 => new Player1Actions(this);

    // Player2
    private readonly InputActionMap m_Player2;
    private IPlayer2Actions m_Player2ActionsCallbackInterface;
    private readonly InputAction m_Player2_P2_ToggleCover;
    private readonly InputAction m_Player2_P2_Aim;
    private readonly InputAction m_Player2_P2_Fire;
    public struct Player2Actions
    {
        private @DefaultControls m_Wrapper;
        public Player2Actions(@DefaultControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @P2_ToggleCover => m_Wrapper.m_Player2_P2_ToggleCover;
        public InputAction @P2_Aim => m_Wrapper.m_Player2_P2_Aim;
        public InputAction @P2_Fire => m_Wrapper.m_Player2_P2_Fire;
        public InputActionMap Get() { return m_Wrapper.m_Player2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player2Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer2Actions instance)
        {
            if (m_Wrapper.m_Player2ActionsCallbackInterface != null)
            {
                @P2_ToggleCover.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnP2_ToggleCover;
                @P2_ToggleCover.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnP2_ToggleCover;
                @P2_ToggleCover.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnP2_ToggleCover;
                @P2_Aim.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnP2_Aim;
                @P2_Aim.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnP2_Aim;
                @P2_Aim.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnP2_Aim;
                @P2_Fire.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnP2_Fire;
                @P2_Fire.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnP2_Fire;
                @P2_Fire.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnP2_Fire;
            }
            m_Wrapper.m_Player2ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @P2_ToggleCover.started += instance.OnP2_ToggleCover;
                @P2_ToggleCover.performed += instance.OnP2_ToggleCover;
                @P2_ToggleCover.canceled += instance.OnP2_ToggleCover;
                @P2_Aim.started += instance.OnP2_Aim;
                @P2_Aim.performed += instance.OnP2_Aim;
                @P2_Aim.canceled += instance.OnP2_Aim;
                @P2_Fire.started += instance.OnP2_Fire;
                @P2_Fire.performed += instance.OnP2_Fire;
                @P2_Fire.canceled += instance.OnP2_Fire;
            }
        }
    }
    public Player2Actions @Player2 => new Player2Actions(this);

    // Player1UI
    private readonly InputActionMap m_Player1UI;
    private IPlayer1UIActions m_Player1UIActionsCallbackInterface;
    private readonly InputAction m_Player1UI_Select;
    private readonly InputAction m_Player1UI_Navitage;
    private readonly InputAction m_Player1UI_Back;
    public struct Player1UIActions
    {
        private @DefaultControls m_Wrapper;
        public Player1UIActions(@DefaultControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Player1UI_Select;
        public InputAction @Navitage => m_Wrapper.m_Player1UI_Navitage;
        public InputAction @Back => m_Wrapper.m_Player1UI_Back;
        public InputActionMap Get() { return m_Wrapper.m_Player1UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1UIActions set) { return set.Get(); }
        public void SetCallbacks(IPlayer1UIActions instance)
        {
            if (m_Wrapper.m_Player1UIActionsCallbackInterface != null)
            {
                @Select.started -= m_Wrapper.m_Player1UIActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_Player1UIActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_Player1UIActionsCallbackInterface.OnSelect;
                @Navitage.started -= m_Wrapper.m_Player1UIActionsCallbackInterface.OnNavitage;
                @Navitage.performed -= m_Wrapper.m_Player1UIActionsCallbackInterface.OnNavitage;
                @Navitage.canceled -= m_Wrapper.m_Player1UIActionsCallbackInterface.OnNavitage;
                @Back.started -= m_Wrapper.m_Player1UIActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_Player1UIActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_Player1UIActionsCallbackInterface.OnBack;
            }
            m_Wrapper.m_Player1UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Navitage.started += instance.OnNavitage;
                @Navitage.performed += instance.OnNavitage;
                @Navitage.canceled += instance.OnNavitage;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
            }
        }
    }
    public Player1UIActions @Player1UI => new Player1UIActions(this);

    // Player2UI
    private readonly InputActionMap m_Player2UI;
    private IPlayer2UIActions m_Player2UIActionsCallbackInterface;
    private readonly InputAction m_Player2UI_Select;
    private readonly InputAction m_Player2UI_Navitage;
    private readonly InputAction m_Player2UI_Back;
    public struct Player2UIActions
    {
        private @DefaultControls m_Wrapper;
        public Player2UIActions(@DefaultControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Player2UI_Select;
        public InputAction @Navitage => m_Wrapper.m_Player2UI_Navitage;
        public InputAction @Back => m_Wrapper.m_Player2UI_Back;
        public InputActionMap Get() { return m_Wrapper.m_Player2UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player2UIActions set) { return set.Get(); }
        public void SetCallbacks(IPlayer2UIActions instance)
        {
            if (m_Wrapper.m_Player2UIActionsCallbackInterface != null)
            {
                @Select.started -= m_Wrapper.m_Player2UIActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_Player2UIActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_Player2UIActionsCallbackInterface.OnSelect;
                @Navitage.started -= m_Wrapper.m_Player2UIActionsCallbackInterface.OnNavitage;
                @Navitage.performed -= m_Wrapper.m_Player2UIActionsCallbackInterface.OnNavitage;
                @Navitage.canceled -= m_Wrapper.m_Player2UIActionsCallbackInterface.OnNavitage;
                @Back.started -= m_Wrapper.m_Player2UIActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_Player2UIActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_Player2UIActionsCallbackInterface.OnBack;
            }
            m_Wrapper.m_Player2UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Navitage.started += instance.OnNavitage;
                @Navitage.performed += instance.OnNavitage;
                @Navitage.canceled += instance.OnNavitage;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
            }
        }
    }
    public Player2UIActions @Player2UI => new Player2UIActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface IPlayer1Actions
    {
        void OnP1_ToggleCover(InputAction.CallbackContext context);
        void OnP1_Aim(InputAction.CallbackContext context);
        void OnP1_Fire(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
    public interface IPlayer2Actions
    {
        void OnP2_ToggleCover(InputAction.CallbackContext context);
        void OnP2_Aim(InputAction.CallbackContext context);
        void OnP2_Fire(InputAction.CallbackContext context);
    }
    public interface IPlayer1UIActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnNavitage(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
    public interface IPlayer2UIActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnNavitage(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
}
